# Generated by Django 3.2.6 on 2021-09-02 17:40

import app1.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2', '0006_auto_20210902_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='filed_by',
            field=models.ForeignKey(blank=True, default=app1.models.MyUser, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created', to=settings.AUTH_USER_MODEL),
        ),
    ]
